delete from TeacherGroups
delete from GroupCourses
delete from TeacherCourses
delete from HomeWorks
delete from GroupCourses
delete from Comments
delete from Teachers
delete from Courses
delete from Groups
delete from ProcessedHomeWorks
delete from Students